pull_request_rules:
  #######################
  # MERGE PRECONDITIONS
  #######################
  - name: label PRs with conflicts
    conditions:
      - conflict
    actions:
      label:
        add:
          - has conflicts
  - name: remove has conflicts label if conflicts got resolved
    conditions:
      - label~=has conflicts
      - -conflict
    actions:
      label:
        remove:
          - has conflicts
  - name: let @adrianjost recreate dependabot PRs with conflicts
    conditions:
      - author~=dependabot(-preview)?\[bot\]
      - conflict
    actions:
      comment:
        message: "@adrianjost tell dependabot to recreate PR"

  #######################
  # AUTO MERGING
  #######################
  - name: auto merge passing Dependabot pull requests
    conditions:
      # match dependabot[bot] and dependabot-preview[bot]
      - author~=dependabot(-preview)?\[bot\]
    actions:
      merge:
        method: squash
        strict: smart
  - name: auto merge when ready to merge label is set
    conditions:
      - label=ready to merge
    actions:
      merge:
        method: merge
        strict: smart

  #######################
  # CLEANUP AFTER MERGE
  #######################
  - name: remove ready to merge when merged
    conditions:
      - merged
      - label=ready to merge
    actions:
      label:
        remove:
          - ready to merge
  - name: delete merged branches
    conditions:
      - merged
      - label!=WIP
    actions:
      delete_head_branch: {}