language: node_js
branches:
  only:
    - master
node_js:
  - "10"
  - "12"
  - "lts/*"
install:
  - npm ci
script:
  - npm run test
  - npx codecov
  - npm run build
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
notifications:
  email: false
cache: npm
