language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
node_js:
  - "8"
  - "10"
  - "lts/*"
  - "node"
install:
  - yarn install --production=false
  - yarn global add codecov
script:
  - yarn test
  - codecov
  - yarn build
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
notifications:
  email: false
cache: yarn
