language: node_js
branches:
  only:
    - master
node_js:
  - "6"
  - "8"
  - "10"
  - "lts/*"
  - "node"
install:
  - yarn install --production=false
  - yarn global add codecov
script:
  - yarn test
  - codecov
  - yarn build
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
notifications:
  email: false
cache:
  directories:
    - node_modules
